### ISSUE TITLE
This is cool! Can I download it via Gradle? 

### ISSUE THREAD

**Issue by andreasmarkussen** [kryanod/ktlint-junit-reporter#1]
We run a kotlin / android / gradle project and it would be cool to get our ktlint reports more visible.

**Comment by kryanod** [comment]
I've been proctastinating with this answer for a really long time, but hey, better late than never. It seems like the [recommended](https://github.com/pinterest/ktlint#creating-a-reporter) way of using a custom reporter is now exactly how I described it in the README. So the answer to your question is: I'm afraid the only way to use a custom reporter now is to manually download the jar. The maven dependency resolution has been deprecated.
